server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # proxy API requests to backend service
    location /account {
        proxy_pass http://backend.backend-local:8080/account;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}